#example
#ansible-playbook install_
#test yes
---
- hosts: apps
  become: yes
  vars:
    ansible_sudo_passs: "{{ ansible_pass }}"
   
  tasks:
    - name: install puppet
      yum:
        name: puppetserver
        state: present

    # a
    - name: add server.xl
      template:
        src: install_and_configure_tomcat_server_server.xml.j2
        dest: /etc/tomcat/server.xml

    - name: start services tomcat
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - puppetserver

