
- name: Using Ansible Conditionals
  hosts: all
  variables:
     file1:
     file2:
     file3:
     origin: "/usr/src/sysops"
     destination: "/opt/sysops"
     permission: "0755"
  tasks:
  - name: "copy 1"
    copy:
      src: "{{ origin }}/{{ file1 }}"
      dest: "{{ destination }}/{{ file1 }}"  
      user: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "{{ permission }}"
    when ansible_nodename == stapp01

  - name: "copy 2"
      src: "{{ origin }}/{{ file2 }}"
      dest: "{{ destination }}/{{ file2 }}"  
      user: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "{{ permission }}"
    when ansible_nodename == stapp02

  - name: "copy 3"
      src: "{{ origin }}/{{ file3 }}"
      dest: "{{ destination }}/{{ file3 }}"  
      user: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "{{ permission }}"
    when ansible_nodename == stapp03


