#example
#ansible-playbook selinux_installatioin.yml --extra-vars="status_selinux=disabled host=stapp01"
#test no
---
- hosts: "{{ host }}"
  become: yes
  vars:
    ansible_sudo_passs: "{{ ansible_pass }}"
    packages: 
      - yum install 
      - policycoreutils 
      - policycoreutils-python 
      - selinux-policy 
      - selinux-policy-targeted 
      - libselinux-utils 
      - setroubleshoot-server 
      - setools setools-console 
      - mcstrans 
   
  tasks:
    - name: install package
      yum:
         name: "{{ item }}"
         state: present
      with_items: "{{ packages }}"

    - name: add /etc/selinux/config
      template:
        src: selinux_installation_config.j2
        dest: /etc/selinux/config


