#ansible-playbook web_server_security.yml
#test pass
---
- hosts: apps
  become: yes
  vars:
    ansible_sudo_passs: "{{ ansible_pass }}"
  tasks:
    - name: add httpd.conf
      template:
        src: web_server_security_http.conf.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: restart httpd 
      systemd:
        name: httpd
        state: restarted

