apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    resources:
      requests:
        memory: "15Mi"
        cpu: "1"
      limits:
        memory: "20Mi"
        cpu: "2"
