#example
#ansible-playbook install_
#test no
---
- hosts: bastion
  become: yes
  vars:
    ansible_sudo_passs: "{{ ansible_pass }}"
   
  tasks:
    - name: Add repository
      yum_repository:
        name: puppet
        description: puppet6
        baseurl: https://yum.puppet.com/puppet6-release-el-7.noarch.rpm

    - name: install puppet
      yum:
        name: puppetserver
        state: present
    
    - name: set xms
      template:
        src: puppetserver.j2
        dest: "/etc/sysconfig/puppetserver"

    - name: start services tomcat
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - puppetserver

