---
- name: create yum repo for puppet
  hosts: jump_host
  vars:
    class_name:
    programming:
    dest:
    repo_source:
    repo_name:
    repo_id:
    package_name:

  task:
    - name: "Create {{ programming }} for template"
      template:
        src: localyum.pp.j2
        dest: "{{ dest }}/{{ programming}}"

    - name: "apply {{ programming }}"
      shell: puppet apply {{ dest }}/{{ programming }}

- name: execute on arguments
  hosts: apps
  tasks:
    - name: puppet agent -t
      shell: puppet agent -t
      register: puppet_agent_output

    - debug: var=puppet_agent_output.stdout_lines

    - name: verifico el repo
      shell: yum repolist
      register: yum_repolist_output

    - debug: var=yum_repolist_output.stdout_lines
